
-- Airbnb Revenue Intelligence Platform | Schema
-- Designed for PostgreSQL. Import data/raw/airbnb_wa.csv into stg_airbnb_listings first.

DROP TABLE IF EXISTS stg_airbnb_listings;
CREATE TABLE stg_airbnb_listings (
    id BIGINT PRIMARY KEY,
    listing_url TEXT,
    scrape_id TEXT,
    last_scraped DATE,
    source TEXT,
    name TEXT,
    description TEXT,
    neighborhood_overview TEXT,
    picture_url TEXT,
    host_id BIGINT,
    host_url TEXT,
    host_name TEXT,
    host_since DATE,
    host_location TEXT,
    host_about TEXT,
    host_response_time TEXT,
    host_response_rate TEXT,
    host_acceptance_rate TEXT,
    host_is_superhost TEXT,
    host_thumbnail_url TEXT,
    host_picture_url TEXT,
    host_neighbourhood TEXT,
    host_listings_count NUMERIC,
    host_total_listings_count NUMERIC,
    host_verifications TEXT,
    host_has_profile_pic TEXT,
    host_identity_verified TEXT,
    neighbourhood TEXT,
    neighbourhood_cleansed TEXT,
    neighbourhood_group_cleansed TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    property_type TEXT,
    room_type TEXT,
    accommodates INT,
    bathrooms NUMERIC,
    bathrooms_text TEXT,
    bedrooms NUMERIC,
    beds NUMERIC,
    amenities TEXT,
    price TEXT,
    minimum_nights INT,
    maximum_nights INT,
    availability_30 INT,
    availability_60 INT,
    availability_90 INT,
    availability_365 INT,
    number_of_reviews INT,
    number_of_reviews_ltm INT,
    number_of_reviews_l30d INT,
    first_review DATE,
    last_review DATE,
    review_scores_rating NUMERIC,
    review_scores_accuracy NUMERIC,
    review_scores_cleanliness NUMERIC,
    review_scores_checkin NUMERIC,
    review_scores_communication NUMERIC,
    review_scores_location NUMERIC,
    review_scores_value NUMERIC,
    license TEXT,
    instant_bookable TEXT,
    calculated_host_listings_count INT,
    reviews_per_month NUMERIC
);
